# Configuracion compartida servida por el Config Server a TODOS los microservicios
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true
